import type { PurchaseOrder, SalesOrder } from "./types"

// Mock suppliers
export const mockSuppliers = [
  {
    id: "1",
    name: "Acme Supplies",
    email: "orders@acmesupplies.com",
    phone: "555-123-4567",
    address: "123 Supplier St, Vendor City, VC 12345",
  },
  {
    id: "2",
    name: "Global Parts Inc.",
    email: "sales@globalparts.com",
    phone: "555-987-6543",
    address: "456 Component Ave, Parts Town, PT 67890",
  },
  {
    id: "3",
    name: "Tech Components Ltd.",
    email: "info@techcomponents.com",
    phone: "555-456-7890",
    address: "789 Tech Blvd, Component City, CC 54321",
  },
]

// Mock customers
export const mockCustomers = [
  {
    id: "1",
    name: "ABC Construction Co.",
    email: "orders@abcconstruction.com",
    phone: "555-111-2222",
    address: "100 Builder Way, Construction City, CC 11111",
  },
  {
    id: "2",
    name: "XYZ Builders",
    email: "purchasing@xyzbuilders.com",
    phone: "555-333-4444",
    address: "200 Developer Rd, Builder Town, BT 22222",
  },
  {
    id: "3",
    name: "City Development Corp.",
    email: "procurement@citydevelopment.com",
    phone: "555-555-6666",
    address: "300 Urban St, Metropolis, MP 33333",
  },
]

// Mock purchase orders
export const mockPurchaseOrders: PurchaseOrder[] = [
  {
    id: "po-1",
    orderNumber: "PO-2025-001",
    supplier: mockSuppliers[0],
    orderDate: "2025-06-01",
    expectedDeliveryDate: "2025-06-15",
    status: "pending",
    items: [
      {
        id: "po-item-1",
        name: "Widget A",
        type: "Accessory",
        sku: "WA-001",
        description: "Standard widget for industrial use",
        orderedQty: 10,
        receivedQty: 0,
        unitPrice: 19.99,
        totalPrice: 199.9,
      },
      {
        id: "po-item-2",
        name: "Gadget X",
        type: "Host",
        sku: "GX-003",
        description: "High-performance gadget with extended warranty",
        orderedQty: 5,
        receivedQty: 0,
        unitPrice: 49.99,
        totalPrice: 249.95,
      },
      {
        id: "po-item-3",
        name: "Component Z",
        type: "Attachment",
        sku: "CZ-005",
        description: "Compatible component for Widget A and Gadget X",
        orderedQty: 15,
        receivedQty: 0,
        unitPrice: 9.99,
        totalPrice: 149.85,
      },
    ],
    notes: "Priority order for upcoming project",
  },
  {
    id: "po-2",
    orderNumber: "PO-2025-002",
    supplier: mockSuppliers[1],
    orderDate: "2025-06-03",
    expectedDeliveryDate: "2025-06-18",
    status: "pending",
    items: [
      {
        id: "po-item-4",
        name: "Widget B",
        type: "Accessory",
        sku: "WB-002",
        description: "Premium widget with enhanced durability",
        orderedQty: 8,
        receivedQty: 0,
        unitPrice: 29.99,
        totalPrice: 239.92,
      },
      {
        id: "po-item-5",
        name: "Gadget Y",
        type: "Host",
        sku: "GY-004",
        description: "Standard gadget for commercial applications",
        orderedQty: 3,
        receivedQty: 0,
        unitPrice: 59.99,
        totalPrice: 179.97,
      },
    ],
    notes: "Regular monthly order",
  },
  {
    id: "po-3",
    orderNumber: "PO-2025-003",
    supplier: mockSuppliers[2],
    orderDate: "2025-06-05",
    expectedDeliveryDate: "2025-06-20",
    status: "partial",
    items: [
      {
        id: "po-item-6",
        name: "Accessory A",
        type: "Accessory",
        sku: "AA-006",
        description: "Compatible accessory for all gadget models",
        orderedQty: 12,
        receivedQty: 8,
        unitPrice: 9.99,
        totalPrice: 119.88,
      },
      {
        id: "po-item-7",
        name: "Accessory B",
        type: "Accessory",
        sku: "AB-007",
        description: "Premium accessory with extended functionality",
        orderedQty: 6,
        receivedQty: 0,
        unitPrice: 14.99,
        totalPrice: 89.94,
      },
    ],
    notes: "Expedited shipping requested",
  },
]

// Mock sales orders
export const mockSalesOrders: SalesOrder[] = [
  {
    id: "so-1",
    orderNumber: "SO-2025-001",
    customer: mockCustomers[0],
    orderDate: "2025-06-02",
    expectedShipDate: "2025-06-10",
    status: "pending",
    items: [
      {
        id: "so-item-1",
        name: "Widget A",
        type: "Accessory",
        sku: "WA-001",
        description: "Standard widget for industrial use",
        orderedQty: 5,
        shippedQty: 0,
        unitPrice: 24.99,
        totalPrice: 124.95,
      },
      {
        id: "so-item-2",
        name: "Gadget X",
        type: "Host",
        sku: "GX-003",
        description: "High-performance gadget with extended warranty",
        orderedQty: 2,
        shippedQty: 0,
        unitPrice: 59.99,
        totalPrice: 119.98,
      },
    ],
    notes: "Customer requested delivery before June 15",
  },
  {
    id: "so-2",
    orderNumber: "SO-2025-002",
    customer: mockCustomers[1],
    orderDate: "2025-06-04",
    expectedShipDate: "2025-06-12",
    status: "pending",
    items: [
      {
        id: "so-item-3",
        name: "Widget B",
        type: "Accessory",
        sku: "WB-002",
        description: "Premium widget with enhanced durability",
        orderedQty: 4,
        shippedQty: 0,
        unitPrice: 34.99,
        totalPrice: 139.96,
      },
      {
        id: "so-item-4",
        name: "Component Z",
        type: "Attachment",
        sku: "CZ-005",
        description: "Compatible component for Widget A and Gadget X",
        orderedQty: 10,
        shippedQty: 0,
        unitPrice: 12.99,
        totalPrice: 129.9,
      },
    ],
    notes: "Regular customer, priority shipping",
  },
  {
    id: "so-3",
    orderNumber: "SO-2025-003",
    customer: mockCustomers[2],
    orderDate: "2025-06-06",
    expectedShipDate: "2025-06-14",
    status: "partial",
    items: [
      {
        id: "so-item-5",
        name: "Gadget Y",
        type: "Host",
        sku: "GY-004",
        description: "Standard gadget for commercial applications",
        orderedQty: 1,
        shippedQty: 0,
        unitPrice: 69.99,
        totalPrice: 69.99,
      },
      {
        id: "so-item-6",
        name: "Accessory A",
        type: "Accessory",
        sku: "AA-006",
        description: "Compatible accessory for all gadget models",
        orderedQty: 5,
        shippedQty: 3,
        unitPrice: 14.99,
        totalPrice: 74.95,
      },
    ],
    notes: "New customer, include product documentation",
  },
]
