import type { Product } from "./types"

export const mockProducts: Product[] = [
  {
    djj_code: "DJJ001",
    status: "Active",
    supplier: "Toyota Material Handling",
    manufacturer_code: "TMH-001",
    category: "Machine",
    subcategory: "Forklift",
    tertiary_category: "Electric",
    name_cn: "电动叉车",
    name_en: "Electric Forklift",
    specs: "2T/3M",
    standards: "CE, ISO",
    unit: "Unit",
    currency: "AUD",
    rrp_price: 25000,
    standard_warranty: "12 months",
    remarks: "Popular model",
    weight_kg: 2500,
    lift_capacity_kg: 2000,
    lift_height_mm: 3000,
    power_source: "Electric",
    other_specs: "Side shift, LED lights",
    warranty: "12 months parts and labor",
    marketing_info: "Best selling electric forklift",
    training_docs: "Operation manual, safety guide",
    syd_stock: 5,
    per_stock: 3,
    bne_stock: 2,
    last_update: "2024-01-15T10:30:00Z",
    last_modified_by: "John Smith",
    product_url: "https://example.com/product/djj001",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-15T10:30:00Z",
    monthly_sales: 12,
    total_sales: 145,
    profit_margin: 0.25,
    images: [
      {
        id: "1",
        url: "/placeholder.svg?height=400&width=600",
        alt: "Electric Forklift - Front View",
        is_primary: true,
      },
      {
        id: "2",
        url: "/placeholder.svg?height=400&width=600",
        alt: "Electric Forklift - Side View",
        is_primary: false,
      },
      {
        id: "3",
        url: "/placeholder.svg?height=400&width=600",
        alt: "Electric Forklift - Interior",
        is_primary: false,
      },
    ],
    sales_data: [
      { month: "Jan", sales: 8, revenue: 200000, profit: 50000 },
      { month: "Feb", sales: 12, revenue: 300000, profit: 75000 },
      { month: "Mar", sales: 15, revenue: 375000, profit: 93750 },
      { month: "Apr", sales: 10, revenue: 250000, profit: 62500 },
      { month: "May", sales: 18, revenue: 450000, profit: 112500 },
      { month: "Jun", sales: 14, revenue: 350000, profit: 87500 },
    ],
  },
  {
    djj_code: "DJJ002",
    status: "Active",
    supplier: "Hyster",
    manufacturer_code: "HYS-002",
    category: "Parts",
    subcategory: "Engine",
    tertiary_category: "Filter",
    name_cn: "空气滤芯",
    name_en: "Air Filter",
    specs: "Standard size",
    standards: "OEM",
    unit: "Piece",
    currency: "AUD",
    rrp_price: 45,
    standard_warranty: "6 months",
    remarks: "OEM quality",
    weight_kg: 0.5,
    warranty: "6 months",
    marketing_info: "High quality replacement part",
    training_docs: "Installation guide",
    syd_stock: 50,
    per_stock: 30,
    bne_stock: 25,
    last_update: "2024-01-10T14:20:00Z",
    last_modified_by: "Jane Doe",
    product_url: "https://example.com/product/djj002",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-10T14:20:00Z",
    monthly_sales: 85,
    total_sales: 1250,
    profit_margin: 0.4,
    images: [
      {
        id: "1",
        url: "/placeholder.svg?height=400&width=600",
        alt: "Air Filter - Product View",
        is_primary: true,
      },
      {
        id: "2",
        url: "/placeholder.svg?height=400&width=600",
        alt: "Air Filter - Packaging",
        is_primary: false,
      },
    ],
    sales_data: [
      { month: "Jan", sales: 120, revenue: 5400, profit: 2160 },
      { month: "Feb", sales: 95, revenue: 4275, profit: 1710 },
      { month: "Mar", sales: 110, revenue: 4950, profit: 1980 },
      { month: "Apr", sales: 88, revenue: 3960, profit: 1584 },
      { month: "May", sales: 102, revenue: 4590, profit: 1836 },
      { month: "Jun", sales: 85, revenue: 3825, profit: 1530 },
    ],
  },
  {
    djj_code: "DJJ003",
    status: "Inactive",
    supplier: "Crown Equipment",
    manufacturer_code: "CRN-003",
    category: "Tools",
    subcategory: "Maintenance",
    tertiary_category: "Diagnostic",
    name_cn: "诊断工具",
    name_en: "Diagnostic Tool",
    specs: "Digital display",
    standards: "ISO 9001",
    unit: "Set",
    currency: "AUD",
    rrp_price: 850,
    standard_warranty: "24 months",
    remarks: "Professional grade",
    weight_kg: 2.5,
    warranty: "24 months",
    marketing_info: "Professional diagnostic equipment",
    training_docs: "User manual, training video",
    syd_stock: 2,
    per_stock: 1,
    bne_stock: 0,
    last_update: "2024-01-05T09:15:00Z",
    last_modified_by: "Mike Johnson",
    product_url: "https://example.com/product/djj003",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-05T09:15:00Z",
    monthly_sales: 3,
    total_sales: 28,
    profit_margin: 0.35,
    images: [
      {
        id: "1",
        url: "/placeholder.svg?height=400&width=600",
        alt: "Diagnostic Tool - Main Device",
        is_primary: true,
      },
    ],
    sales_data: [
      { month: "Jan", sales: 2, revenue: 1700, profit: 595 },
      { month: "Feb", sales: 4, revenue: 3400, profit: 1190 },
      { month: "Mar", sales: 3, revenue: 2550, profit: 892.5 },
      { month: "Apr", sales: 1, revenue: 850, profit: 297.5 },
      { month: "May", sales: 5, revenue: 4250, profit: 1487.5 },
      { month: "Jun", sales: 3, revenue: 2550, profit: 892.5 },
    ],
  },
  {
    djj_code: "DJJ004",
    status: "Active",
    supplier: "Caterpillar",
    manufacturer_code: "CAT-004",
    category: "Machine",
    subcategory: "Excavator",
    tertiary_category: "Mini",
    name_cn: "小型挖掘机",
    name_en: "Mini Excavator",
    specs: "1.5T/2.5M",
    standards: "CE, EPA",
    unit: "Unit",
    currency: "AUD",
    rrp_price: 45000,
    standard_warranty: "24 months",
    remarks: "Compact design",
    weight_kg: 1500,
    lift_capacity_kg: 1500,
    lift_height_mm: 2500,
    power_source: "Diesel",
    other_specs: "Rubber tracks, quick coupler",
    warranty: "24 months comprehensive",
    marketing_info: "Perfect for tight spaces",
    training_docs: "Operation manual, maintenance guide",
    syd_stock: 3,
    per_stock: 2,
    bne_stock: 1,
    last_update: "2024-01-20T16:45:00Z",
    last_modified_by: "Sarah Wilson",
    product_url: "https://example.com/product/djj004",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-20T16:45:00Z",
    monthly_sales: 6,
    total_sales: 42,
    profit_margin: 0.22,
    images: [
      {
        id: "1",
        url: "/placeholder.svg?height=400&width=600",
        alt: "Mini Excavator - Working",
        is_primary: true,
      },
      {
        id: "2",
        url: "/placeholder.svg?height=400&width=600",
        alt: "Mini Excavator - Side Profile",
        is_primary: false,
      },
    ],
    sales_data: [
      { month: "Jan", sales: 4, revenue: 180000, profit: 39600 },
      { month: "Feb", sales: 7, revenue: 315000, profit: 69300 },
      { month: "Mar", sales: 5, revenue: 225000, profit: 49500 },
      { month: "Apr", sales: 8, revenue: 360000, profit: 79200 },
      { month: "May", sales: 6, revenue: 270000, profit: 59400 },
      { month: "Jun", sales: 6, revenue: 270000, profit: 59400 },
    ],
  },
  {
    djj_code: "DJJ005",
    status: "Active",
    supplier: "JCB",
    manufacturer_code: "JCB-005",
    category: "Accessories",
    subcategory: "Attachment",
    tertiary_category: "Bucket",
    name_cn: "挖斗",
    name_en: "Excavator Bucket",
    specs: "600mm width",
    standards: "ISO, JIS",
    unit: "Piece",
    currency: "AUD",
    rrp_price: 1200,
    standard_warranty: "12 months",
    remarks: "Heavy duty construction",
    weight_kg: 85,
    warranty: "12 months wear parts excluded",
    marketing_info: "Durable steel construction",
    training_docs: "Installation and safety guide",
    syd_stock: 8,
    per_stock: 5,
    bne_stock: 3,
    last_update: "2024-01-18T11:30:00Z",
    last_modified_by: "Tom Brown",
    product_url: "https://example.com/product/djj005",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-18T11:30:00Z",
    monthly_sales: 15,
    total_sales: 89,
    profit_margin: 0.3,
    images: [
      {
        id: "1",
        url: "/placeholder.svg?height=400&width=600",
        alt: "Excavator Bucket - Main View",
        is_primary: true,
      },
    ],
    sales_data: [
      { month: "Jan", sales: 12, revenue: 14400, profit: 4320 },
      { month: "Feb", sales: 18, revenue: 21600, profit: 6480 },
      { month: "Mar", sales: 14, revenue: 16800, profit: 5040 },
      { month: "Apr", sales: 16, revenue: 19200, profit: 5760 },
      { month: "May", sales: 15, revenue: 18000, profit: 5400 },
      { month: "Jun", sales: 15, revenue: 18000, profit: 5400 },
    ],
  },
  {
    djj_code: "DJJ006",
    status: "Discontinued",
    supplier: "Komatsu",
    manufacturer_code: "KOM-006",
    category: "Parts",
    subcategory: "Hydraulic",
    tertiary_category: "Pump",
    name_cn: "液压泵",
    name_en: "Hydraulic Pump",
    specs: "Variable displacement",
    standards: "ISO 4401",
    unit: "Unit",
    currency: "AUD",
    rrp_price: 3500,
    standard_warranty: "18 months",
    remarks: "Discontinued model",
    weight_kg: 45,
    warranty: "18 months limited",
    marketing_info: "High efficiency pump",
    training_docs: "Service manual",
    syd_stock: 1,
    per_stock: 0,
    bne_stock: 1,
    last_update: "2024-01-12T13:20:00Z",
    last_modified_by: "Lisa Chen",
    product_url: "https://example.com/product/djj006",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-12T13:20:00Z",
    monthly_sales: 2,
    total_sales: 15,
    profit_margin: 0.28,
    images: [
      {
        id: "1",
        url: "/placeholder.svg?height=400&width=600",
        alt: "Hydraulic Pump - Component View",
        is_primary: true,
      },
    ],
    sales_data: [
      { month: "Jan", sales: 1, revenue: 3500, profit: 980 },
      { month: "Feb", sales: 3, revenue: 10500, profit: 2940 },
      { month: "Mar", sales: 2, revenue: 7000, profit: 1960 },
      { month: "Apr", sales: 1, revenue: 3500, profit: 980 },
      { month: "May", sales: 2, revenue: 7000, profit: 1960 },
      { month: "Jun", sales: 2, revenue: 7000, profit: 1960 },
    ],
  },
  {
    djj_code: "DJJ007",
    status: "Active",
    supplier: "Liebherr",
    manufacturer_code: "LIE-007",
    category: "Machine",
    subcategory: "Crane",
    tertiary_category: "Mobile",
    name_cn: "移动式起重机",
    name_en: "Mobile Crane",
    specs: "50T/40M",
    standards: "CE, ANSI",
    unit: "Unit",
    currency: "AUD",
    rrp_price: 125000,
    standard_warranty: "36 months",
    remarks: "Heavy duty crane",
    weight_kg: 45000,
    lift_capacity_kg: 50000,
    lift_height_mm: 40000,
    power_source: "Diesel",
    other_specs: "All-terrain, telescopic boom",
    warranty: "36 months comprehensive",
    marketing_info: "Professional grade mobile crane",
    training_docs: "Operation manual, safety certification",
    syd_stock: 1,
    per_stock: 1,
    bne_stock: 0,
    last_update: "2024-01-25T14:30:00Z",
    last_modified_by: "David Lee",
    product_url: "https://example.com/product/djj007",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-25T14:30:00Z",
    monthly_sales: 1,
    total_sales: 8,
    profit_margin: 0.18,
    images: [
      {
        id: "1",
        url: "/placeholder.svg?height=400&width=600",
        alt: "Mobile Crane - Construction Site",
        is_primary: true,
      },
      {
        id: "2",
        url: "/placeholder.svg?height=400&width=600",
        alt: "Mobile Crane - Extended Boom",
        is_primary: false,
      },
    ],
    sales_data: [
      { month: "Jan", sales: 1, revenue: 125000, profit: 22500 },
      { month: "Feb", sales: 2, revenue: 250000, profit: 45000 },
      { month: "Mar", sales: 1, revenue: 125000, profit: 22500 },
      { month: "Apr", sales: 1, revenue: 125000, profit: 22500 },
      { month: "May", sales: 2, revenue: 250000, profit: 45000 },
      { month: "Jun", sales: 1, revenue: 125000, profit: 22500 },
    ],
  },
  {
    djj_code: "DJJ008",
    status: "Active",
    supplier: "Volvo",
    manufacturer_code: "VOL-008",
    category: "Machine",
    subcategory: "Loader",
    tertiary_category: "Wheel",
    name_cn: "轮式装载机",
    name_en: "Wheel Loader",
    specs: "3T/3.5M",
    standards: "CE, EPA",
    unit: "Unit",
    currency: "AUD",
    rrp_price: 85000,
    standard_warranty: "24 months",
    remarks: "Fuel efficient model",
    weight_kg: 12000,
    lift_capacity_kg: 3000,
    lift_height_mm: 3500,
    power_source: "Diesel",
    other_specs: "Load sensing hydraulics, air conditioning",
    warranty: "24 months parts and labor",
    marketing_info: "Efficient and reliable wheel loader",
    training_docs: "Operation manual, maintenance schedule",
    syd_stock: 2,
    per_stock: 3,
    bne_stock: 1,
    last_update: "2024-01-22T09:45:00Z",
    last_modified_by: "Emma Wilson",
    product_url: "https://example.com/product/djj008",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-22T09:45:00Z",
    monthly_sales: 4,
    total_sales: 28,
    profit_margin: 0.2,
    images: [
      {
        id: "1",
        url: "/placeholder.svg?height=400&width=600",
        alt: "Wheel Loader - Construction",
        is_primary: true,
      },
    ],
    sales_data: [
      { month: "Jan", sales: 3, revenue: 255000, profit: 51000 },
      { month: "Feb", sales: 5, revenue: 425000, profit: 85000 },
      { month: "Mar", sales: 4, revenue: 340000, profit: 68000 },
      { month: "Apr", sales: 6, revenue: 510000, profit: 102000 },
      { month: "May", sales: 4, revenue: 340000, profit: 68000 },
      { month: "Jun", sales: 4, revenue: 340000, profit: 68000 },
    ],
  },
]
